name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: Extract version
        id: version
        run: echo "VERSION=$(yq '.info.version' openapi.yaml)" >> "$GITHUB_OUTPUT"
      - name: Check if tag exists
        id: check
        run: |
          if git rev-parse "refs/tags/${{ steps.version.outputs.VERSION }}" >/dev/null 2>&1; then
            echo "EXISTS=true" >> "$GITHUB_OUTPUT"
          else
            echo "EXISTS=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Tag release
        if: steps.check.outputs.EXISTS == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ steps.version.outputs.VERSION }} -m "Release ${{ steps.version.outputs.VERSION }}"
          git push origin ${{ steps.version.outputs.VERSION }}
      - name: Create release
        if: steps.check.outputs.EXISTS == 'false'
        run: |
          gh release create ${{ steps.version.outputs.VERSION }} --title ${{ steps.version.outputs.VERSION }} --notes "Release ${{ steps.version.outputs.VERSION }}"
          gh release upload ${{ steps.version.outputs.VERSION }} openapi.yaml